name: 'medicare_claims'
version: '1.0.0'
config-version: 2

profile: 'medicare_claims'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medicare_claims:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
      +schema: "{{ env_var('BQ_MARTS_DATASET', 'medicare_marts') }}"

seeds:
  medicare_claims:
    +schema: "{{ env_var('BQ_STAGING_DATASET', 'medicare_staging') }}"
    ssa_state_codes:
      +column_types:
        state_code: string
